version: '3.9'

services:
  crud_backend:
    container_name: crud_backend
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=901861
      - PG_DB=crud_react
      - PG_HOST=localhost
      - PG_PORT=5432
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=901861
      - POSTGRES_DB=crud_react
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
