# Generated by Django 5.0.6 on 2024-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ph_no',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, default='img/profile/default_profile.jpg', upload_to='img/profile'),
        ),
    ]
